package com.combatreforged.metis.api.world.command;

public enum CommandType {
    ADVANCEMENT, ATTRIBUTE, EXECUTE, BOSS_BAR, CLEAR_INVENTORY, CLONE, DATA, DATA_PACK, DEBUG, DEFAULT_GAMEMODE, DIFFICULTY,
    EFFECT, EMOTE, ENCHANT, EXPERIENCE, FILL, FORCE_LOAD, FUNCTION, GAMEMODE, GAMERULE, GIVE, HELP, KICK, KILL, LIST, LOCATE,
    LOCATE_BIOME, LOOT, MSG, PARTICLE, PLAY_SOUND, RELOAD, RECIPE, REPLACE_ITEM, SAY, SCHEDULE, SCOREBOARD, SET_BLOCK, SET_SPAWN,
    SET_WORLD_SPAWN, SPECTATE, SPREAD_PLAYERS, STOP_SOUND, SUMMON, TAG, TEAM, TEAM_MSG, TELEPORT, TELL_RAW, TIME, TITLE, TRIGGER,
    WEATHER, WORLD_BORDER, BAN_IP, BAN_LIST, BAN_PLAYER, DE_OP, OP, PARDON, PARDON_IP, SAVE_ALL, SAVE_OFF, SAVE_ON, SET_PLAYER_IDLE_TIMEOUT,
    STOP, WHITELIST;
}
